name: Pipeline CI-CD Practica 2

on:
  push:
    branches: [ main ]

jobs:
  integracion-continua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar permisos
        run: chmod +x scripts/test.sh

      - name: Validar archivos
        run: |
          test -f Dockerfile
          test -f docker-compose.yml
          test -f app/index.html

      - name: Ejecutar Pruebas
        run: sh scripts/test.sh

      - name: Build Imagen
        run: docker build -t cicd-web-demo:staging .